import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { FairyEngine } from './FairyEngine';
import { CHALLENGES, validateChallengeDefinition } from './challenges';
import { verifyChallenge, verifyHints, VerificationResult } from './challenges/verify';

const write = process.argv.includes('--write');
const engine = new FairyEngine();
const results: VerificationResult[] = [];
try {
  await engine.waitReady();
  for (const definition of CHALLENGES) {
    validateChallengeDefinition(definition);
    const result = await verifyChallenge(definition, engine);
    if (!write) await verifyHints(definition, result.hints);
    results.push(result);
    console.log(`${definition.order}. ${definition.name}: PASS, minimum ${result.referenceMinimumMoves} player moves, ${result.opponentRepliesVerified} opponent replies, ${result.positionsQueried} positions`);
    for (const check of result.requiredAbilityChecks ?? []) console.log(`  Required ability: ${check.upgradeId} at ${check.position}; ordinary piece has no forced solution (${check.positionsQueried} control positions)`);
  }
  if (write) {
    const hints = Object.fromEntries(results.map(result => [result.id, result.hints]));
    await writeFile(fileURLToPath(new URL('./challenges/verified-hints.ts', import.meta.url)), `import { Move } from '../../../shared/types';\n// Generated by verify:challenges -- --write. Do not edit answers manually.\nexport const verifiedHints: Record<string, Record<string, Move[]>> = ${JSON.stringify(hints, null, 2)};\n`);
    await writeFile(fileURLToPath(new URL('../../CHALLENGE_VERIFICATION.json', import.meta.url)), JSON.stringify({ schemaVersion: 1, engineVariant: 'customxiangqi', coverage: 'All legal opponent replies along a proven strategy; every budget-valid loadout; bounded player moves; ordinary-piece counterproofs for declared required abilities. Not historical reachability or a complete enumeration of all player solutions.', results }, null, 2) + '\n');
  }
  console.log(`Verified ${results.length} challenges. ${write ? 'Hints and report written.' : 'Shipped hints match proof.'}`);
} finally { engine.destroy(); }
