import { define, move, position } from './model';

// Authored challenge positions; all replies are proved by verify:challenges.
export const advanced = [
  define({ id: 'back-rank-net', name: '隔障合圍', order: 13, chapter: 4, difficulty: '挑戰',
    themes: ['天馬', '馬腳', '車馬配合'], learningPoint: '辨認阻擋與跳躍控制如何改變最後的封鎖。',
    description: '敵炮卡住接近九宮的路線，安排攻擊順序，在 3 步內完成將殺。', contentVersion: 2,
    initialFen: position({ d0: 'K', e9: 'k', g6: 'U', g7: 'R', f6: 'c' }), goal: { type: 'CHECKMATE' },
    requiredUpgrades: [{ position: 'g6', upgradeId: 'TIAN_MA' }],
    goalText: '玩家 3 步內將死黑方', maxPlayerMoves: 3,
    directionHint: '先用車收窄九宮，再比較天馬與普通馬能否越過敵炮所在的馬腳。',
    preferredMoves: [move('g7', 'e7'), move('e7', 'e8'), move('g6', 'e7')],
    commonMistake: '急著吃掉擋路的炮，反而浪費建立封鎖的先手。',
    completionExplanation: '車先進入 e 線並收緊逃路，天馬再依防守轉位。敵炮留在 f6 時，g6 → e7 的馬腳被占用，只有天馬能跳過；不必先清除障礙。' }),
  define({ id: 'initiative-race', name: '貼宮追擊', order: 14, chapter: 4, difficulty: '挑戰',
    themes: ['霰彈砲', '近身威脅', '車炮配合'], learningPoint: '利用不同距離的攻擊能力銜接連續威脅。',
    description: '黑將仍有退路，讓攻擊棋子接力，在 3 步內完成將殺。', contentVersion: 2,
    initialFen: position({ d0: 'K', e9: 'k', b9: 'M', h6: 'R', g5: 'N', g6: 'p' }), goal: { type: 'CHECKMATE' },
    requiredUpgrades: [{ position: 'b9', upgradeId: 'PO_JI_PAO' }],
    goalText: '玩家 3 步內將死黑方', maxPlayerMoves: 3,
    directionHint: '先把黑將逼離底線，再找出霰彈砲能無需炮架、貼身將軍的位置。',
    preferredMoves: [move('h6', 'h9'), move('b9', 'e9'), move('h9', 'h7'), move('h9', 'f9')],
    commonMistake: '一直等待炮架，忽略霰彈砲可以直接威脅正交相鄰的黑將。',
    completionExplanation: '車 h6 → h9 逼將下移，霰彈砲 b9 → e9 用貼身能力將軍；普通炮沒有炮架便不能形成這個威脅。最後車依黑將退到 e7 或 f8 調整封鎖。' }),
  define({ id: 'elephant-interlock', name: '斜線交錯', order: 15, chapter: 4, difficulty: '挑戰',
    themes: ["飛象","車炮","防守分支"], learningPoint: '比較棋子轉位後的間接威脅與逃路變化。',
    description: '在 3 步內完成將殺；請根據對手實際回應調整走法。', contentVersion: 2,
    initialFen: position({"e0":"K","e9":"k","e4":"P","b6":"R","e5":"C","c8":"F","i6":"p"}), goal: { type: 'CHECKMATE' },
    goalText: '玩家 3 步內將死黑方', maxPlayerMoves: 3,
    directionHint: '比較飛象轉位後能否成為炮架，再找出能配合中路炮封宮的車線。',
    preferredMoves: [move('c8', 'e6'), move('b6', 'b2'), move('b2', 'f2'), move('b2', 'd2')],
    commonMistake: '只用車追將，沒有先建立中路控制，讓黑將轉入另一側。',
    completionExplanation: '飛象 c8 → e6 成為炮架，由 e5 的炮將軍並控制中路；車再轉線，依黑將走向 d 線或 f 線完成封宮。飛象本身不直接將軍。' }),
  define({ id: 'cannon-crossfire', name: '雙炮換線', order: 16, chapter: 4, difficulty: '挑戰',
    themes: ["霰彈砲","傳統炮","防守分支"], learningPoint: '推演兩種攻擊能力如何銜接。',
    description: '在 3 步內完成將殺；請根據對手實際回應調整走法。',
    initialFen: position({"e0":"K","e9":"k","e4":"P","a5":"R","g7":"C","b6":"M","a6":"p"}), goal: { type: 'CHECKMATE' },
    goalText: '玩家 3 步內將死黑方', maxPlayerMoves: 3,
    directionHint: '分清兩種炮的吃子規則；先限制黑將，再比較可用的炮架。',
    preferredMoves: [move('a5', 'e5'), move('g7', 'f7'), move('b6', 'f6')],
    commonMistake: '把霰彈砲的遠程吃子當成車的吃子，或只沿同一條炮線追擊。',
    completionExplanation: '車先轉入中線限制黑將，傳統炮與霰彈砲再依防守位置換線；近戰與炮架的需求不同，不能套用同一種走法。' }),
  define({ id: 'knight-cannon-weave', name: '跳躍與伏線', order: 17, chapter: 5, difficulty: '高手',
    themes: ["天馬","霰彈砲","防守分支"], learningPoint: '同時計算跳躍威脅與直線控制。',
    description: '在 3 步內完成將殺；請根據對手實際回應調整走法。',
    initialFen: position({"e0":"K","e9":"k","e4":"P","i5":"R","g6":"U","d5":"M","f9":"a"}), goal: { type: 'CHECKMATE' },
    goalText: '玩家 3 步內將死黑方', maxPlayerMoves: 3,
    directionHint: '尋找可以先收窄九宮，再用跳躍補上缺口的配置。',
    preferredMoves: [move('d5', 'd8'), move('g6', 'e5'), move('i5', 'i9')],
    commonMistake: '先用車將軍，卻沒有安排黑將轉位後的接續攻擊。',
    completionExplanation: '霰彈砲先建立控制，天馬再跳轉補上封鎖；車的終結位置取決於黑士與黑將的回應。' }),
  define({ id: 'quiet-knight-entry', name: '未渡伏炮', order: 18, chapter: 5, difficulty: '高手',
    themes: ['突擊兵', '未過河橫移', '車炮配合'], learningPoint: '先安排限制退路的棋子，再建立遠程攻擊的條件。',
    description: '兵還在己方半場，推演車炮與兵如何在 3 步內完成配合。', contentVersion: 2,
    initialFen: position({ d0: 'K', e9: 'k', g3: 'S', f8: 'R', f2: 'C', a6: 'p' }), goal: { type: 'CHECKMATE' },
    requiredUpgrades: [{ position: 'g3', upgradeId: 'TU_JI_BING' }],
    goalText: '玩家 3 步內將死黑方', maxPlayerMoves: 3,
    directionHint: '比較車退到河邊後的封路，再看未過河的突擊兵能否橫移補上炮架。',
    preferredMoves: [move('f8', 'f4'), move('f4', 'e4'), move('g3', 'f3')],
    commonMistake: '過早架炮或只讓兵向前走，沒有先用車控制黑將的逃路。',
    completionExplanation: '車先退到 f4，再轉入 e 線迫將；突擊兵 g3 → f3 在過河前橫移，讓 f2 的炮隔子將軍。普通兵在 g3 不能橫移，無法在三步內保證完成同樣的封宮。' }),
  define({ id: 'four-move-siege', name: '橫兵織網', order: 19, chapter: 5, difficulty: '高手',
    themes: ['突擊兵', '連續橫移', '車炮配合'], learningPoint: '比較準備炮架與直接攻擊的順序，推演防守變化。',
    description: '黑士守住宮門，兵仍未過河；在 4 步內完成協同將殺。', contentVersion: 2,
    initialFen: position({ d0: 'K', e9: 'k', g4: 'S', i5: 'R', e1: 'C', i6: 'p', d9: 'a' }), goal: { type: 'CHECKMATE' },
    requiredUpgrades: [{ position: 'g4', upgradeId: 'TU_JI_BING' }],
    goalText: '玩家 4 步內將死黑方', maxPlayerMoves: 4,
    directionHint: '先處理側翼的干擾，再看突擊兵能否在己方半場連續橫移，接上中路炮線。',
    preferredMoves: [move('i5', 'i6'), move('i6', 'f6'), move('g4', 'f4'), move('f4', 'e4')],
    commonMistake: '讓兵先向前渡河，或不看黑士的防守便照固定順序架炮，導致步數不足。',
    completionExplanation: '車先吃 i6 的卒，再依黑將與黑士的位置調整封路；突擊兵能在第 4 橫線連續橫移。黑士留在 d9 的分支可用 g4 → f4 → e4 接通炮線，黑士轉位時需改變車炮配合。普通兵必須先過河，四步內無法保證將殺。' }),
  define({ id: 'knight-return-net', name: '越障追將', order: 20, chapter: 5, difficulty: '高手',
    themes: ['天馬', '馬腳', '連續轉位'], learningPoint: '保留跳躍的先手，再依防守調整後續控制格。',
    description: '敵炮擋住天馬的出路；在多種防守下，用 4 步完成車馬合圍。', contentVersion: 2,
    initialFen: position({ d0: 'K', e9: 'k', a6: 'U', f8: 'R', b6: 'c' }), goal: { type: 'CHECKMATE' },
    requiredUpgrades: [{ position: 'a6', upgradeId: 'TIAN_MA' }],
    goalText: '玩家 4 步內將死黑方', maxPlayerMoves: 4,
    directionHint: '先比較 a6 → c7 的馬腳限制，再推演黑炮移動或將軍時如何保留車馬配合。',
    preferredMoves: [move('a6', 'c7'), move('f8', 'e8'), move('c7', 'e6'), move('e6', 'g7')],
    commonMistake: '先花一步處理擋路的炮，或忽略黑炮轉線後對紅帥的威脅。',
    completionExplanation: '天馬先越過 b6 的敵炮，由 a6 跳至 c7；普通馬會被蹩腳。之後車與天馬依黑將、黑炮的回應調整；若黑炮將軍，須先合法應將，不能只照一條固定路線追將。' }),
];
