import { define, move, position } from './model';

// Authored challenge positions; all replies are proved by verify:challenges.
export const advanced = [
  define({ id: 'back-rank-net', name: '宮門暗線', order: 13, chapter: 4, difficulty: '挑戰',
    themes: ["車兵","封路","防守分支"], learningPoint: '比較強制回應與逃路變化。',
    description: '在 3 步內完成將殺；請根據對手實際回應調整走法。',
    initialFen: position({"e0":"K","e9":"k","e4":"P","b6":"R","g6":"N","b5":"C","g9":"P","e8":"a","a5":"r"}), goal: { type: 'CHECKMATE' },
    goalText: '玩家 3 步內將死黑方', maxPlayerMoves: 3,
    directionHint: '不要只看眼前的將軍；比較過河兵移動後留下的控制格。',
    preferredMoves: [move('b6', 'b9'), move('g9', 'f9'), move('b9', 'b8')],
    commonMistake: '連續追將卻讓黑將逃向下一排，忽略過河兵能改變封鎖。',
    completionExplanation: '車先轉到底線迫使黑方應對，再以兵縮小逃路；黑將下移時，車必須同步轉到相應橫線。' }),
  define({ id: 'initiative-race', name: '先手之爭', order: 14, chapter: 4, difficulty: '挑戰',
    themes: ["車","反擊","防守分支"], learningPoint: '判斷進攻與處理敵方威脅的先後順序。',
    description: '在 3 步內完成將殺；請根據對手實際回應調整走法。',
    initialFen: position({"e0":"K","e9":"k","e4":"P","b7":"R","g7":"N","f9":"C","b9":"P","b6":"r"}), goal: { type: 'CHECKMATE' },
    goalText: '玩家 3 步內將死黑方', maxPlayerMoves: 3,
    directionHint: '比較敵車留在盤上和被清除後，黑方能採取的防守。',
    preferredMoves: [move('b7', 'b6'), move('b6', 'c6'), move('c6', 'd6')],
    commonMistake: '只向九宮衝刺，讓敵車保留反擊或擋將的手段。',
    completionExplanation: '先清除 b6 的敵車，再沿黑將的退路調整己車；黑將留在底線或下移時，最後的封鎖走法不同。' }),
  define({ id: 'elephant-interlock', name: '斜線交錯', order: 15, chapter: 4, difficulty: '挑戰',
    themes: ["飛象","車炮","防守分支"], learningPoint: '計算多種走法對同一片區域的控制。',
    description: '在 3 步內完成將殺；請根據對手實際回應調整走法。',
    initialFen: position({"e0":"K","e9":"k","e4":"P","b7":"R","d9":"N","e7":"C","i9":"F","f7":"a","a6":"p"}), goal: { type: 'CHECKMATE' },
    goalText: '玩家 3 步內將死黑方', maxPlayerMoves: 3,
    directionHint: '比較飛象的斜線與車的橫線能否連續限制黑將，再檢查炮與馬保護的格子。',
    preferredMoves: [move('i9', 'g7'), move('b7', 'b8')],
    commonMistake: '只看車的直接攻擊，忽略飛象將軍後對手有不止一種退路。',
    completionExplanation: '飛象 i9 → g7 重整斜線控制，車再跟隨黑將的位置封鎖；黑方留在底線、退到 e8 或繼續退宮，需採取不同後續。' }),
  define({ id: 'cannon-crossfire', name: '雙炮換線', order: 16, chapter: 4, difficulty: '挑戰',
    themes: ["霰彈砲","傳統炮","防守分支"], learningPoint: '推演兩種攻擊能力如何銜接。',
    description: '在 3 步內完成將殺；請根據對手實際回應調整走法。',
    initialFen: position({"e0":"K","e9":"k","e4":"P","a5":"R","g7":"C","b6":"M","a6":"p"}), goal: { type: 'CHECKMATE' },
    goalText: '玩家 3 步內將死黑方', maxPlayerMoves: 3,
    directionHint: '分清兩種炮的吃子規則；先限制黑將，再比較可用的炮架。',
    preferredMoves: [move('a5', 'e5'), move('g7', 'f7'), move('b6', 'f6')],
    commonMistake: '把霰彈砲的遠程吃子當成車的吃子，或只沿同一條炮線追擊。',
    completionExplanation: '車先轉入中線限制黑將，傳統炮與霰彈砲再依防守位置換線；近戰與炮架的需求不同，不能套用同一種走法。' }),
  define({ id: 'knight-cannon-weave', name: '跳躍與伏線', order: 17, chapter: 5, difficulty: '高手',
    themes: ["天馬","霰彈砲","防守分支"], learningPoint: '同時計算跳躍威脅與直線控制。',
    description: '在 3 步內完成將殺；請根據對手實際回應調整走法。',
    initialFen: position({"e0":"K","e9":"k","e4":"P","i5":"R","g6":"U","d5":"M","f9":"a"}), goal: { type: 'CHECKMATE' },
    goalText: '玩家 3 步內將死黑方', maxPlayerMoves: 3,
    directionHint: '尋找可以先收窄九宮，再用跳躍補上缺口的配置。',
    preferredMoves: [move('d5', 'd8'), move('g6', 'e5'), move('i5', 'i9')],
    commonMistake: '先用車將軍，卻沒有安排黑將轉位後的接續攻擊。',
    completionExplanation: '霰彈砲先建立控制，天馬再跳轉補上封鎖；車的終結位置取決於黑士與黑將的回應。' }),
  define({ id: 'quiet-knight-entry', name: '迂迴入局', order: 18, chapter: 5, difficulty: '高手',
    themes: ["馬","車炮","防守分支"], learningPoint: '比較準備走步與立即吃子的後續結果。',
    description: '在 3 步內完成將殺；請根據對手實際回應調整走法。',
    initialFen: position({"e0":"K","e9":"k","e4":"P","a7":"R","a9":"N","b7":"C","g8":"S","e8":"a","a6":"p"}), goal: { type: 'CHECKMATE' },
    goalText: '玩家 3 步內將死黑方', maxPlayerMoves: 3,
    directionHint: '先考慮馬轉位對九宮的影響，再決定車是否吃卒。',
    preferredMoves: [move('a9', 'c8'), move('a7', 'a6'), move('a6', 'f6')],
    commonMistake: '看到可吃的卒就立刻吃，少了馬在後續將殺中的控制。',
    completionExplanation: '馬先由 a9 轉入 c8，然後車處理側翼並追蹤黑將；有些防守需要炮接手，有些由車完成封宮。' }),
  define({ id: 'four-move-siege', name: '四步圍城', order: 19, chapter: 5, difficulty: '高手',
    themes: ["突擊兵","車馬","防守分支"], learningPoint: '保持連續走步之間的協調，推演完整防守分支。',
    description: '在 4 步內完成將殺；請根據對手實際回應調整走法。',
    initialFen: position({"e0":"K","e9":"k","e4":"P","c6":"R","a5":"N","g7":"S","f9":"a","d7":"a"}), goal: { type: 'CHECKMATE' },
    goalText: '玩家 4 步內將死黑方', maxPlayerMoves: 4,
    directionHint: '每走一步都重新數黑將的逃格；留意兵的橫移與馬腳。',
    preferredMoves: [move('c6', 'c9'), move('g7', 'f7'), move('f7', 'e7'), move('a5', 'c6')],
    commonMistake: '只記住一條路線，忽略黑士移動會改變黑將的退路和馬腳。',
    completionExplanation: '車轉入底線後，突擊兵逐步收緊九宮，馬再依黑士的位置完成控制；必須依黑方回應調整順序。' }),
  define({ id: 'knight-return-net', name: '回馬成網', order: 20, chapter: 5, difficulty: '高手',
    themes: ["天馬","車炮","防守分支"], learningPoint: '計算轉位後的威脅，以及對手延長抵抗的方式。',
    description: '在 4 步內完成將殺；請根據對手實際回應調整走法。',
    initialFen: position({"e0":"K","e9":"k","e4":"P","b5":"R","d9":"U","i5":"C","c6":"p"}), goal: { type: 'CHECKMATE' },
    goalText: '玩家 4 步內將死黑方', maxPlayerMoves: 4,
    directionHint: '比較天馬離開底線後能控制的格子，不要急著把車送進九宮。',
    preferredMoves: [move('d9', 'c7'), move('b5', 'b9')],
    commonMistake: '直接用車追將，忽略天馬原位與轉位後對逃格的控制不同。',
    completionExplanation: '天馬先轉位形成新的控制網，車炮再依黑將的回應封鎖；最頑強的防守需要四次玩家走步才能將殺。' }),
];
