import { define, move, position } from './model';
export const basics = [
  define({ id: 'rook-mate', name: '一擊封宮', order: 1, chapter: 1, difficulty: '入門', themes: ['將殺', '車'],
    learningPoint: '分辨將軍與將死，利用保護和封路完成最後一擊。',
    description: '車兵配合包圍黑將，找出一步將死的走法。', contentVersion: 3,
    initialFen: position({ e9: 'k', d8: 'R', e8: 'a', f8: 'P', e7: 'R', e0: 'K' }),
    goal: { type: 'CHECKMATE' }, goalText: '玩家 1 步內將死黑方', maxPlayerMoves: 1,
    directionHint: '觀察黑將的逃路，以及哪一枚攻擊棋子有同伴保護。',
    preferredMoves: [move('e7', 'e8')], commonMistake: '只形成將軍，卻沒有封住逃路或保護攻擊棋子。',
    completionExplanation: '中路車吃士將軍，左側車與右側過河兵控制逃路並保護中路車，黑將無法應將。' }),
  define({ id: 'hunt-shotgun', name: '追擊霰彈砲', order: 2, chapter: 1, difficulty: '入門', themes: ['捕獲', '天馬', '車'],
    learningPoint: '認識指定捕獲目標；不同合法解法都能通關。',
    description: '找出直接吃掉指定霰彈砲的走法，天馬與車都有機會。',
    initialFen: position({ e9: 'k', e6: 'p', a5: 'R', d5: 'm', c3: 'U', e0: 'K' }),
    goal: { type: 'CAPTURE', targetSquare: 'd5' }, goalText: '玩家 2 步內吃掉指定霰彈砲', maxPlayerMoves: 2,
    directionHint: '比較跳躍攻擊與沒有阻擋的直線攻擊路線。', preferredMoves: [move('c3', 'd5'), move('a5', 'd5')],
    commonMistake: '先走無關棋子，讓目標獲得移動或反擊的機會。',
    completionExplanation: '天馬 c3 → d5 與車 a5 → d5 都能直接吃掉目標，判定不限於提示答案。' }),
  define({ id: 'knight-loadout', name: '突破馬腳', order: 3, chapter: 1, difficulty: '入門', themes: ['天馬', '構築'],
    learningPoint: '天馬能跳過馬腳阻擋，普通馬則不能。',
    description: '己方兵擋住馬腳，先在局前選擇天馬升級。',
    initialFen: position({ e9: 'k', e6: 'p', d5: 'm', c4: 'P', c3: 'N', e0: 'K' }),
    goal: { type: 'CAPTURE', targetSquare: 'd5' }, goalText: '玩家 1 步內吃掉指定霰彈砲', maxPlayerMoves: 1,
    budget: 3, allowedUpgrades: [{ position: 'c3', upgradeId: 'TIAN_MA' }], referenceLoadouts: [{ position: 'c3', upgradeId: 'TIAN_MA' }],
    directionHint: '檢查普通馬的馬腳，再比較天馬的跳躍能力。', preferredMoves: [move('c3', 'd5')],
    commonMistake: '沒有升級就開局，普通馬仍受己方兵阻擋。',
    completionExplanation: 'c3 的天馬可越過 c4 的己方兵，直接跳至 d5 吃掉目標。' }),
  define({ id: 'elephant-cross', name: '飛象渡河', order: 4, chapter: 1, difficulty: '入門', themes: ['飛象', '構築'],
    learningPoint: '飛象可跨河，但仍須留意象眼阻擋。',
    description: '目標位於河對岸，用升級後的飛象完成捕獲。', contentVersion: 2,
    initialFen: position({ e9: 'k', e6: 'p', e0: 'K', c4: 'B', a6: 'p' }),
    goal: { type: 'CAPTURE', targetSquare: 'a6' }, goalText: '玩家 1 步內吃掉河對岸的卒', maxPlayerMoves: 1,
    budget: 2, allowedUpgrades: [{ position: 'c4', upgradeId: 'FEI_XIANG' }], referenceLoadouts: [{ position: 'c4', upgradeId: 'FEI_XIANG' }],
    directionHint: '目標在斜向兩格的位置；考慮跨河限制與中間的象眼。', preferredMoves: [move('c4', 'a6')],
    commonMistake: '把飛象當成天馬，忽略飛象仍有象眼限制。',
    completionExplanation: '升級飛象後，c4 → a6 能跨河捕獲；b5 象眼為空，走法合法。' }),
];
