import { define, move, position } from './model';
export const construction = [
  define({ id: 'budget-choice', name: '三點的抉擇', order: 9, chapter: 3, difficulty: '綜合', themes: ['天馬', '飛象', '預算'],
    learningPoint: '升級要服務於目標，花費較少不代表能解題。', description: '預算無法同時升級馬與象，選擇能立即捕獲目標的能力。', contentVersion: 2,
    initialFen: position({ e9: 'k', e6: 'p', e0: 'K', c3: 'N', c4: 'P', g0: 'B', d5: 'c' }),
    goal: { type: 'CAPTURE', targetSquare: 'd5' }, goalText: '玩家 1 步內吃掉指定炮', maxPlayerMoves: 1,
    budget: 3, allowedUpgrades: [{ position: 'c3', upgradeId: 'TIAN_MA' }, { position: 'g0', upgradeId: 'FEI_XIANG' }], referenceLoadouts: [{ position: 'c3', upgradeId: 'TIAN_MA' }],
    directionHint: '先找出能在一步內抵達目標的棋子，再決定預算用途。', preferredMoves: [move('c3', 'd5')],
    commonMistake: '把預算用在遠離目標的飛象，卻留下被蹩腳的普通馬。', completionExplanation: '將 3 點用於 c3 天馬才能越過 c4 馬腳；升級 g0 飛象無法在一步內抵達目標。' }),
  define({ id: 'which-knight', name: '升級哪匹馬', order: 10, chapter: 3, difficulty: '綜合', themes: ['天馬', '位置取捨'],
    learningPoint: '同一種能力在不同位置，對目標的效果不同。', description: '兩匹馬都被擋住馬腳，但只有一匹能立即跳到目標。', contentVersion: 2,
    initialFen: position({ e9: 'k', e6: 'p', e0: 'K', c3: 'N', c4: 'P', g3: 'N', g4: 'P', d5: 'c' }),
    goal: { type: 'CAPTURE', targetSquare: 'd5' }, goalText: '玩家 1 步內吃掉指定炮', maxPlayerMoves: 1,
    budget: 3, allowedUpgrades: [{ position: 'c3', upgradeId: 'TIAN_MA' }, { position: 'g3', upgradeId: 'TIAN_MA' }], referenceLoadouts: [{ position: 'c3', upgradeId: 'TIAN_MA' }],
    directionHint: '比較兩匹馬與目標的座標差；天馬仍只能走日字。', preferredMoves: [move('c3', 'd5')],
    commonMistake: '升級距離不對的馬，誤以為無馬腳就能跳到任何位置。', completionExplanation: 'c3 與 d5 相差一欄兩列，符合天馬跳躍；g3 並不在這條攻擊路線上。' }),
  define({ id: 'build-a-screen', name: '一點串起攻勢', order: 11, chapter: 3, difficulty: '綜合', themes: ['突擊兵', '預算', '配合'],
    learningPoint: '便宜的升級也能串起兩步戰術，預算不必花滿。', description: '在天馬與突擊兵之間做選擇，為傳統炮建立吃子路線。', contentVersion: 2,
    initialFen: position({ e9: 'k', e0: 'K', d1: 'C', c4: 'P', h0: 'N', d7: 'a', e8: 'a' }),
    goal: { type: 'CAPTURE', targetSquare: 'd7' }, goalText: '玩家 2 步內架炮吃掉指定士', maxPlayerMoves: 2,
    budget: 3, allowedUpgrades: [{ position: 'c4', upgradeId: 'TU_JI_BING' }, { position: 'h0', upgradeId: 'TIAN_MA' }], referenceLoadouts: [{ position: 'c4', upgradeId: 'TU_JI_BING' }],
    directionHint: '目標與炮在同一欄，缺少的是炮架；思考哪項升級能補足它。', preferredMoves: [move('c4', 'd4')],
    commonMistake: '花滿 3 點升級遠處的馬，卻沒有補上炮架。', completionExplanation: '只花 1 點升級 c4 突擊兵，橫移至 d4 架炮；e8 的黑士擋住帥將照面，d7 的目標士無法移到已被占用的 e8，炮可在下一步捕獲。' }),
  define({ id: 'palace-finale', name: '封宮架炮', order: 12, chapter: 3, difficulty: '綜合', themes: ['突擊兵', '傳統炮', '將殺'],
    learningPoint: '先準備炮架，再結合其他棋子的封路完成限步將殺。', description: '車馬已控制逃路，還需要突擊兵用兩步補上炮架。', contentVersion: 2,
    initialFen: position({ e9: 'k', e0: 'K', b8: 'N', h8: 'N', f8: 'R', e6: 'C', c7: 'S', a6: 'p' }),
    goal: { type: 'CHECKMATE' }, goalText: '玩家 2 步內將死黑方', maxPlayerMoves: 2,
    directionHint: '先找出黑將的三條逃路由誰控制，再讓突擊兵逐步接近炮的中線。', preferredMoves: [move('c7', 'd7'), move('d7', 'e7')],
    commonMistake: '把控制逃路的車馬移走，或用沒有保護的棋子當炮架。', completionExplanation: '突擊兵 c7 → d7 → e7 建立炮架，炮將軍；b8、h8 的馬控制 d9、f9，f8 的車控制 e8，黑將無法應將。' }),
];
