import { define, move, position } from './model';
export const tactics = [
  define({ id: 'shotgun-close', name: '貼身開火', order: 5, chapter: 2, difficulty: '進階', themes: ['霰彈砲', '捕獲'],
    learningPoint: '霰彈砲可以直接吃掉上下左右相鄰一格的敵子。', description: '沒有炮架也能開火，觀察目標與霰彈砲的距離。',
    initialFen: position({ e9: 'k', e6: 'p', e0: 'K', a2: 'M', b2: 'p' }),
    goal: { type: 'CAPTURE', targetSquare: 'b2' }, goalText: '玩家 1 步內吃掉貼身的卒', maxPlayerMoves: 1,
    directionHint: '近戰能力只涵蓋上下左右相鄰一格，不需要炮架。', preferredMoves: [move('a2', 'b2')],
    commonMistake: '以為所有吃子都要隔一個炮架，錯過貼身攻擊。', completionExplanation: 'a2 → b2 是正交相鄰一格，霰彈砲可直接吃子。' }),
  define({ id: 'shotgun-screen', name: '隔子轟擊', order: 6, chapter: 2, difficulty: '進階', themes: ['霰彈砲', '炮架'],
    learningPoint: '霰彈砲的遠程吃子需要恰好一個炮架。', description: '己方兵可以當炮架；不要先移走它。',
    initialFen: position({ e9: 'k', e6: 'p', e0: 'K', a2: 'M', a4: 'P', a6: 'p' }),
    goal: { type: 'CAPTURE', targetSquare: 'a6' }, goalText: '玩家 1 步內隔子吃掉指定卒', maxPlayerMoves: 1,
    directionHint: '沿同一直線數一數攻擊棋子與目標之間的棋子。', preferredMoves: [move('a2', 'a6')],
    commonMistake: '先移走炮架，或把兩個阻擋棋子也當成可跳越。', completionExplanation: 'a4 的兵是唯一炮架，霰彈砲可從 a2 隔子吃到 a6。' }),
  define({ id: 'soldier-side', name: '未渡先行', order: 7, chapter: 2, difficulty: '進階', themes: ['突擊兵', '構築'],
    learningPoint: '突擊兵未過河就能左右平移與吃子。', description: '敵卒就在側邊，普通兵的前進能力無法完成目標。',
    initialFen: position({ e9: 'k', e6: 'p', e0: 'K', c3: 'P', d3: 'p' }),
    goal: { type: 'CAPTURE', targetSquare: 'd3' }, goalText: '玩家 1 步內橫向吃掉指定卒', maxPlayerMoves: 1,
    budget: 1, allowedUpgrades: [{ position: 'c3', upgradeId: 'TU_JI_BING' }], referenceLoadouts: [{ position: 'c3', upgradeId: 'TU_JI_BING' }],
    directionHint: '比較普通兵與突擊兵在己方半場的橫向能力。', preferredMoves: [move('c3', 'd3')],
    commonMistake: '只想向前走，或以為突擊兵能向後退。', completionExplanation: 'c3 尚未過河，升級後仍能橫移至 d3 捕獲敵卒。' }),
  define({ id: 'screen-team', name: '移兵架炮', order: 8, chapter: 2, difficulty: '進階', themes: ['突擊兵', '傳統炮', '配合'],
    learningPoint: '先用突擊兵建立炮架，再依目標位置完成捕獲。', description: '兩步完成配合；對手推卒時，捕獲位置也要跟著調整。', contentVersion: 2,
    initialFen: position({ f9: 'k', e0: 'K', a1: 'C', b3: 'S', a6: 'p' }),
    goal: { type: 'CAPTURE', targetSquare: 'a6' }, goalText: '玩家 2 步內架炮吃掉指定卒', maxPlayerMoves: 2,
    directionHint: '先把能橫移的棋子放進炮與目標之間，下一回合再看目標是否移動。', preferredMoves: [move('b3', 'a3')],
    commonMistake: '炮直接前進追卒，卻沒有準備吃子所需的炮架。', completionExplanation: '突擊兵移到 a3 成為炮架；無論卒停在 a6 或推進 a5，炮都能隔子捕獲。' }),
];
