import { Move } from '../../../shared/types';
// Generated by verify:challenges -- --write. Do not edit answers manually.
export const verifiedHints: Record<string, Record<string, Move[]>> = {
  "rook-mate": {
    "4k4/3RaP3/4R4/9/9/9/9/9/9/4K4 w": [
      {
        "from": "e7",
        "to": "e8"
      }
    ]
  },
  "hunt-shotgun": {
    "4k4/9/9/4p4/R2m5/9/2U6/9/9/4K4 w": [
      {
        "from": "a5",
        "to": "d5"
      },
      {
        "from": "c3",
        "to": "d5"
      }
    ]
  },
  "knight-loadout": {
    "4k4/9/9/4p4/3m5/2P6/2U6/9/9/4K4 w": [
      {
        "from": "c3",
        "to": "d5"
      }
    ]
  },
  "elephant-cross": {
    "4k4/9/9/p3p4/9/2F6/9/9/9/4K4 w": [
      {
        "from": "c4",
        "to": "a6"
      }
    ]
  },
  "shotgun-close": {
    "4k4/9/9/4p4/9/9/9/Mp7/9/4K4 w": [
      {
        "from": "a2",
        "to": "b2"
      }
    ]
  },
  "shotgun-screen": {
    "4k4/9/9/p3p4/9/P8/9/M8/9/4K4 w": [
      {
        "from": "a2",
        "to": "a6"
      }
    ]
  },
  "soldier-side": {
    "4k4/9/9/4p4/9/9/2Sp5/9/9/4K4 w": [
      {
        "from": "c3",
        "to": "d3"
      }
    ]
  },
  "screen-team": {
    "5k3/9/9/9/p8/9/S8/9/C8/4K4 w": [
      {
        "from": "a1",
        "to": "a5"
      }
    ],
    "9/5k3/9/p8/9/9/S8/9/C8/4K4 w": [
      {
        "from": "a1",
        "to": "a6"
      }
    ],
    "5k3/9/9/p8/9/9/1S7/9/C8/4K4 w": [
      {
        "from": "b3",
        "to": "a3"
      }
    ]
  },
  "budget-choice": {
    "4k4/9/9/4p4/3c5/2P6/2U6/9/9/4K1B2 w": [
      {
        "from": "c3",
        "to": "d5"
      }
    ]
  },
  "which-knight": {
    "4k4/9/9/4p4/3c5/2P3P2/2U3N2/9/9/4K4 w": [
      {
        "from": "c3",
        "to": "d5"
      }
    ]
  },
  "build-a-screen": {
    "5k3/4a4/3a5/9/9/3S5/9/9/3C5/4K2N1 w": [
      {
        "from": "d1",
        "to": "d7"
      }
    ],
    "3k5/4a4/3a5/9/9/3S5/9/9/3C5/4K2N1 w": [
      {
        "from": "d1",
        "to": "d7"
      }
    ],
    "4k4/4a4/3a5/9/9/2S6/9/9/3C5/4K2N1 w": [
      {
        "from": "c4",
        "to": "d4"
      }
    ]
  },
  "palace-finale": {
    "4k4/1N3R1N1/3S5/4C4/p8/9/9/9/9/4K4 w": [
      {
        "from": "d7",
        "to": "e7"
      }
    ],
    "4k4/1N3R1N1/2S6/p3C4/9/9/9/9/9/4K4 w": [
      {
        "from": "c7",
        "to": "d7"
      }
    ]
  },
  "back-rank-net": {
    "1R1a1P3/4k4/9/6N2/rC7/4P4/9/9/9/4K4 w": [
      {
        "from": "b9",
        "to": "b8"
      }
    ],
    "1R1a1k3/9/9/6N2/rC7/4P4/9/9/9/4K4 w": [
      {
        "from": "b9",
        "to": "d9"
      }
    ],
    "1R1ak1P2/9/9/6N2/rC7/4P4/9/9/9/4K4 w": [
      {
        "from": "g9",
        "to": "f9"
      }
    ],
    "4k1P2/4a4/9/1R4N2/rC7/4P4/9/9/9/4K4 w": [
      {
        "from": "b6",
        "to": "b9"
      }
    ]
  },
  "initiative-race": {
    "1P3C3/3k5/6N2/2R6/9/4P4/9/9/9/4K4 w": [
      {
        "from": "c6",
        "to": "d6"
      }
    ],
    "1P2kC3/9/6N2/2R6/9/4P4/9/9/9/4K4 w": [
      {
        "from": "c6",
        "to": "c9"
      }
    ],
    "1P1k1C3/9/6N2/1R7/9/4P4/9/9/9/4K4 w": [
      {
        "from": "b6",
        "to": "c6"
      }
    ],
    "1P2kC3/9/1R4N2/1r7/9/4P4/9/9/9/4K4 w": [
      {
        "from": "b7",
        "to": "b6"
      }
    ]
  },
  "elephant-interlock": {
    "5k3/9/9/4F4/4C3p/4P4/9/1R7/9/4K4 w": [
      {
        "from": "b2",
        "to": "f2"
      }
    ],
    "9/5k3/9/4F3p/4C4/4P4/9/1R7/9/4K4 w": [
      {
        "from": "b2",
        "to": "f2"
      }
    ],
    "5k3/9/9/1R2F3p/4C4/4P4/9/9/9/4K4 w": [
      {
        "from": "b6",
        "to": "b2"
      }
    ],
    "3k5/9/9/4F4/4C3p/4P4/9/1R7/9/4K4 w": [
      {
        "from": "b2",
        "to": "d2"
      }
    ],
    "9/3k5/9/4F3p/4C4/4P4/9/1R7/9/4K4 w": [
      {
        "from": "b2",
        "to": "d2"
      }
    ],
    "3k5/9/9/1R2F3p/4C4/4P4/9/9/9/4K4 w": [
      {
        "from": "b6",
        "to": "b2"
      }
    ],
    "4k4/2F6/9/1R6p/4C4/4P4/9/9/9/4K4 w": [
      {
        "from": "c8",
        "to": "e6"
      }
    ]
  },
  "cannon-crossfire": {
    "5k3/9/5C3/1M7/p3R4/4P4/9/9/9/4K4 w": [
      {
        "from": "b6",
        "to": "f6"
      }
    ],
    "9/5k3/5C3/pM7/4R4/4P4/9/9/9/4K4 w": [
      {
        "from": "b6",
        "to": "f6"
      }
    ],
    "5k3/9/6C2/pM7/4R4/4P4/9/9/9/4K4 w": [
      {
        "from": "g7",
        "to": "f7"
      }
    ],
    "3k5/9/3C5/1M7/p3R4/4P4/9/9/9/4K4 w": [
      {
        "from": "b6",
        "to": "d6"
      }
    ],
    "9/3k5/3C5/pM7/4R4/4P4/9/9/9/4K4 w": [
      {
        "from": "b6",
        "to": "d6"
      }
    ],
    "3k5/9/6C2/pM7/4R4/4P4/9/9/9/4K4 w": [
      {
        "from": "g7",
        "to": "d7"
      }
    ],
    "4k4/9/6C2/pM7/R8/4P4/9/9/9/4K4 w": [
      {
        "from": "a5",
        "to": "e5"
      }
    ]
  },
  "knight-cannon-weave": {
    "4k4/3M5/3a5/9/4U3R/4P4/9/9/9/4K4 w": [
      {
        "from": "i5",
        "to": "i9"
      }
    ],
    "4k4/3M5/5a3/9/4U3R/4P4/9/9/9/4K4 w": [
      {
        "from": "i5",
        "to": "i9"
      }
    ],
    "3ak4/3M5/9/9/4U3R/4P4/9/9/9/4K4 w": [
      {
        "from": "i5",
        "to": "i9"
      }
    ],
    "4ka3/3M5/9/9/4U3R/4P4/9/9/9/4K4 w": [
      {
        "from": "e5",
        "to": "d7"
      }
    ],
    "5k3/3Ma4/9/9/4U3R/4P4/9/9/9/4K4 w": [
      {
        "from": "i5",
        "to": "i9"
      }
    ],
    "4k4/3Ma4/9/6U2/8R/4P4/9/9/9/4K4 w": [
      {
        "from": "g6",
        "to": "e5"
      }
    ],
    "4ka3/9/9/6U2/3M4R/4P4/9/9/9/4K4 w": [
      {
        "from": "d5",
        "to": "d8"
      }
    ]
  },
  "quiet-knight-entry": {
    "5k3/2N3S2/1C1a5/R8/9/4P4/9/9/9/4K4 w": [
      {
        "from": "a6",
        "to": "f6"
      }
    ],
    "5k3/2N3S2/1C3a3/R8/9/4P4/9/9/9/4K4 w": [
      {
        "from": "a6",
        "to": "a9"
      }
    ],
    "3a1k3/2N3S2/1C7/R8/9/4P4/9/9/9/4K4 w": [
      {
        "from": "a6",
        "to": "f6"
      }
    ],
    "5k3/2N1a1S2/RC7/p8/9/4P4/9/9/9/4K4 w": [
      {
        "from": "a7",
        "to": "a6"
      }
    ],
    "3k5/1CN3S2/R2a5/p8/9/4P4/9/9/9/4K4 w": [
      {
        "from": "a7",
        "to": "d7"
      }
    ],
    "3k5/1CN3S2/R4a3/p8/9/4P4/9/9/9/4K4 w": [
      {
        "from": "a7",
        "to": "d7"
      }
    ],
    "3k1a3/1CN3S2/R8/p8/9/4P4/9/9/9/4K4 w": [
      {
        "from": "a7",
        "to": "d7"
      }
    ],
    "3k5/1CN1a1S2/R8/9/p8/4P4/9/9/9/4K4 w": [
      {
        "from": "a7",
        "to": "a9"
      }
    ],
    "3k5/2N1a1S2/RC7/p8/9/4P4/9/9/9/4K4 w": [
      {
        "from": "b7",
        "to": "b8"
      }
    ],
    "N3k4/4a1S2/RC7/p8/9/4P4/9/9/9/4K4 w": [
      {
        "from": "a9",
        "to": "c8"
      }
    ]
  },
  "four-move-siege": {
    "2R2a3/3ka4/4S4/9/N8/4P4/9/9/9/4K4 w": [
      {
        "from": "a5",
        "to": "c6"
      }
    ],
    "2R6/3ka4/3aS4/9/N8/4P4/9/9/9/4K4 w": [
      {
        "from": "a5",
        "to": "c6"
      }
    ],
    "2R2a3/3k5/3a1S3/9/N8/4P4/9/9/9/4K4 w": [
      {
        "from": "f7",
        "to": "e7"
      }
    ],
    "2R2a3/4k4/3a2S2/9/N8/4P4/9/9/9/4K4 w": [
      {
        "from": "g7",
        "to": "f7"
      }
    ],
    "4ka3/9/3a2S2/2R6/N8/4P4/9/9/9/4K4 w": [
      {
        "from": "c6",
        "to": "c9"
      }
    ]
  },
  "knight-return-net": {
    "4k4/9/2U6/9/1Rp5C/4P4/9/9/9/4K4 w": [
      {
        "from": "b5",
        "to": "b9"
      }
    ],
    "1R7/9/5k3/2p1U4/8C/4P4/9/9/9/4K4 w": [
      {
        "from": "b9",
        "to": "b7"
      }
    ],
    "1R7/4k4/9/2p1U4/8C/4P4/9/9/9/4K4 w": [
      {
        "from": "i5",
        "to": "e5"
      }
    ],
    "1R7/5k3/2U6/2p6/8C/4P4/9/9/9/4K4 w": [
      {
        "from": "c7",
        "to": "e6"
      }
    ],
    "5k3/9/2U6/2p6/1R6C/4P4/9/9/9/4K4 w": [
      {
        "from": "b5",
        "to": "b9"
      }
    ],
    "3Uk4/9/9/2p6/1R6C/4P4/9/9/9/4K4 w": [
      {
        "from": "d9",
        "to": "c7"
      }
    ]
  }
};
