import { Move } from '../../../shared/types';
// Generated by verify:challenges -- --write. Do not edit answers manually.
export const verifiedHints: Record<string, Record<string, Move[]>> = {
  "rook-mate": {
    "4k4/3RpR3/4R4/9/9/9/9/9/9/4K4 w": [
      {
        "from": "e7",
        "to": "e8"
      }
    ]
  },
  "hunt-shotgun": {
    "4k4/9/9/4p4/R2m5/9/2U6/9/9/4K4 w": [
      {
        "from": "a5",
        "to": "d5"
      },
      {
        "from": "c3",
        "to": "d5"
      }
    ]
  },
  "knight-loadout": {
    "4k4/9/9/4p4/3m5/2P6/2U6/9/9/4K4 w": [
      {
        "from": "c3",
        "to": "d5"
      }
    ]
  },
  "elephant-cross": {
    "4k4/9/9/p3p4/9/2F6/9/9/9/4K4 w": [
      {
        "from": "c4",
        "to": "a6"
      }
    ]
  },
  "shotgun-close": {
    "4k4/9/9/4p4/9/9/9/Mp7/9/4K4 w": [
      {
        "from": "a2",
        "to": "b2"
      }
    ]
  },
  "shotgun-screen": {
    "4k4/9/9/p3p4/9/P8/9/M8/9/4K4 w": [
      {
        "from": "a2",
        "to": "a6"
      }
    ]
  },
  "soldier-side": {
    "4k4/9/9/4p4/9/9/2Sp5/9/9/4K4 w": [
      {
        "from": "c3",
        "to": "d3"
      }
    ]
  },
  "screen-team": {
    "5k3/9/9/9/p8/9/9/S8/C8/4K4 w": [
      {
        "from": "a1",
        "to": "a5"
      }
    ],
    "9/5k3/9/p8/9/9/9/S8/C8/4K4 w": [
      {
        "from": "a1",
        "to": "a6"
      }
    ],
    "5k3/9/9/p8/9/9/9/1S7/C8/4K4 w": [
      {
        "from": "b2",
        "to": "a2"
      }
    ]
  },
  "budget-choice": {
    "4k4/9/9/4p4/3p5/2P6/2U6/9/9/4K1B2 w": [
      {
        "from": "c3",
        "to": "d5"
      }
    ]
  },
  "which-knight": {
    "4k4/9/9/4p4/3p5/2P3P2/2U3N2/9/9/4K4 w": [
      {
        "from": "c3",
        "to": "d5"
      }
    ]
  },
  "build-a-screen": {
    "5k3/9/9/9/p8/9/9/S8/C8/4K2N1 w": [
      {
        "from": "a1",
        "to": "a5"
      }
    ],
    "9/5k3/9/p8/9/9/9/S8/C8/4K2N1 w": [
      {
        "from": "a1",
        "to": "a6"
      }
    ],
    "5k3/9/9/p8/9/9/9/1S7/C8/4K2N1 w": [
      {
        "from": "b2",
        "to": "a2"
      }
    ]
  },
  "palace-finale": {
    "4k4/1N5N1/3S2N2/4C4/p8/9/9/9/9/4K4 w": [
      {
        "from": "d7",
        "to": "e7"
      }
    ],
    "4k4/1N5N1/2S3N2/p3C4/9/9/9/9/9/4K4 w": [
      {
        "from": "c7",
        "to": "d7"
      }
    ]
  }
};
